### ISSUE TITLE
此处应该是removeEventListener 

### ISSUE THREAD

**Issue by willer-613** [cgfeel/react-rotate-captcha#1]
https://github.com/cgfeel/react-rotate-captcha/blob/e351b25facd986fb9470d8b697e30fde4501ff22/src/components/CaptchaControl.tsx#L59C26-L59C42

**Comment by cgfeel** [comment]
https://github.com/cgfeel/react-rotate-captcha/commit/66897ffcff9a773ac499c2f3ad82099285d4ebbc

@willer-613 已修复，更新到1.0.26
